package de.svenheins.main;

/** influence type only concerns PlayerEntities (Players, Agents (Human and animals)) */
public enum AttributeType {
	LIFE, MAXLIFE, MANA, MAXMANA, SPEED, MAXSPEED, ARMOR, BLOCKCHANCE, STRENGH, 
	LIFEREGENERATION, MANAREGENERATION, ATTACKSPEED, 
	LIGHTRADIUS, LIFEVISIONRADIUS, GOLDVISIONRADIUS,
	VISIBILITY, ANIMALCAMOUFLAGE, HUMANCAMOUFLAGE,
	WILLPOWER, MX, MY
}
